name: Get TamsV2 data

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Required System Image
        run: |
          sdkmanager "system-images;android-30;google_apis;x86"

      - name: Verify System Image Installation
        run: sdkmanager --list | grep "system-images;android-30;google_apis;x86"

      - name: Create and Start Emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --force
          # Start the emulator in the background
          nohup emulator -avd test -no-snapshot -no-audio -no-window &

          # Wait for the emulator to boot
          adb wait-for-device

          # Additional wait to ensure boot completion
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

          # Unlock the emulator screen
          adb shell input keyevent 82

      - name: Download Termux APK
        run: |
          wget https://github.com/termux/termux-app/releases/download/v0.118.1/termux-app_v0.118.1+github-debug_x86.apk -O termux.apk

      - name: Install Termux
        run: |
          adb install termux.apk

      - name: Push Scripts to Emulator
        run: |
          adb push scrapper.py /data/local/tmp/scrapper.py
          adb push setup.sh /data/local/tmp/setup.sh
          adb shell chmod +x /data/local/tmp/setup.sh

      - name: Execute Setup Script in Termux
        run: |
          adb shell am start -n com.termux/.HomeActivity \
            -a com.termux.RUN_COMMAND \
            -e command "bash /data/local/tmp/setup.sh"